# Generated by Django 4.2.5 on 2023-10-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
