# Generated by Django 4.2.6 on 2023-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
